In [ ]:
# à faire :
#importation du fichier depuis s3 vers le service cloud
#structuration des données 
#enregistrement sur le s3 des donnees strucutrées
#detection cancer à l'aide du modele resnet18 entrainées sur le miniddsm

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("shantanughosh/vindr-mammogram-dataset-dicom-to-png")

print("Path to dataset files:", path)

In [ ]:
import os
endpoint_s3 = "s3/lucasvital/stat_app/"
os.system(f"mc mirror {path} {endpoint_s3}")

print(f"Fichiers synchronisés sur S3 à l'adresse : {endpoint_s3}")

In [ ]:
#il faut aussi télécharger le fichier csv des métadonnées à part
#lien du kaggle :  https://www.kaggle.com/datasets/shantanughosh/vindr-mammogram-dataset-dicom-to-png/data

In [ ]:
#on récupère le fichier avec ces commandes dans le terminal : mkdir -p ~/work/dataset_sample puis mc cp -r s3/lucasvital/stat_app/images_png/ ~/work/dataset_sample/
#on récupère aussi le fichier des metadonnées : vindr_detection_v1_folds.csv puis mc cp s3/lucasvital/stat_app/vindr_detection_v1_folds.csv ~/work/metadonnees/

In [1]:
import pandas as pd
df_metadonnees=pd.read_csv("/home/onyxia/work/metadonnees/vindr_detection_v1_folds.csv")
#print(df_metadonnees.head())
df_metadonnees.groupby("breast_birads").count()

/tmp/ipykernel_4147/4091431516.py:2: DtypeWarning: Columns (0: finding_birads) have mixed types. Specify dtype option on import or set low_memory=False.
  df_metadonnees=pd.read_csv("/home/onyxia/work/metadonnees/vindr_detection_v1_folds.csv")

,patient_id,series_id,image_id,laterality,view,height,width,breast_density,finding_categories,finding_birads,...,Focal_Asymmetry,Global_Asymmetry,Mass,Nipple_Retraction,No_Finding,Skin_Retraction,Skin_Thickening,Suspicious_Calcification,Suspicious_Lymph_Node,density
breast_birads,,,,,,,,,,,,,,,,,,,,,
BI-RADS 1,13406,13406,13406,13406,13406,13406,13406,13406,13406,0,...,13406,13406,13406,13406,13406,13406,13406,13406,13406,13406
BI-RADS 2,4676,4676,4676,4676,4676,4676,4676,4676,4676,0,...,4676,4676,4676,4676,4676,4676,4676,4676,4676,4676
BI-RADS 3,972,972,972,972,972,972,972,972,972,842,...,972,972,972,972,972,972,972,972,972,972
BI-RADS 4,1005,1005,1005,1005,1005,1005,1005,1005,1005,917,...,1005,1005,1005,1005,1005,1005,1005,1005,1005,1005
BI-RADS 5,427,427,427,427,427,427,427,427,427,370,...,427,427,427,427,427,427,427,427,427,427

In [2]:
print(df_metadonnees.columns)

Index(['patient_id', 'series_id', 'image_id', 'laterality', 'view', 'height',
       'width', 'breast_birads', 'breast_density', 'finding_categories',
       'finding_birads', 'xmin', 'ymin', 'xmax', 'ymax', 'split',
       'resized_xmin', 'resized_ymin', 'resized_xmax', 'resized_ymax', 'fold',
       'Architectural_Distortion', 'Asymmetry', 'Focal_Asymmetry',
       'Global_Asymmetry', 'Mass', 'Nipple_Retraction', 'No_Finding',
       'Skin_Retraction', 'Skin_Thickening', 'Suspicious_Calcification',
       'Suspicious_Lymph_Node', 'density'],
      dtype='str')

In [3]:
df_metadonnees.head(2)

,patient_id,series_id,image_id,laterality,view,height,width,breast_birads,breast_density,finding_categories,...,Focal_Asymmetry,Global_Asymmetry,Mass,Nipple_Retraction,No_Finding,Skin_Retraction,Skin_Thickening,Suspicious_Calcification,Suspicious_Lymph_Node,density
0,48575a27b7c992427041a82fa750d3fa,26de4993fa6b8ae50a91c8baf49b92b0,4e3a578fe535ea4f5258d3f7f4419db8.png,R,CC,3518,2800,BI-RADS 4,DENSITY C,['Mass'],...,0,0,1,0,0,0,0,0,0,2
1,48575a27b7c992427041a82fa750d3fa,26de4993fa6b8ae50a91c8baf49b92b0,dac39351b0f3a8c670b7f8dc88029364.png,R,MLO,3518,2800,BI-RADS 4,DENSITY C,['Mass'],...,0,0,1,0,0,0,0,0,0,2

In [5]:
pip install tqdm

Collecting tqdm
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm
Successfully installed tqdm-4.67.3
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# on restructure les donées en deux dossier 0 et 1 à l'aide des étiquettes contenues dans le fichier des métadonnées
import os
import shutil
from tqdm import tqdm

os.makedirs("/home/onyxia/work/dataset_vindr",exist_ok=True)
os.makedirs("/home/onyxia/work/dataset_vindr/0-normal",exist_ok=True)
os.makedirs("/home/onyxia/work/dataset_vindr/1-cancer_benign",exist_ok=True)


def restructure_data():
    source="/home/onyxia/work/dataset_sample/"
    destination_cancer_benign="/home/onyxia/work/dataset_vindr/1-cancer_benign"
    destination_normal="/home/onyxia/work/dataset_vindr/0-normal"
    for filename in tqdm(os.listdir(source)):
        subfolder=os.path.join(source,filename)
        for image in os. listdir(subfolder):
            info_image=df_metadonnees[df_metadonnees["image_id"]==image]
            if info_image["view"].iloc[0]=="MLO":
                if info_image["breast_birads"].iloc[0]=="BI-RADS 1":
                    shutil.copy2(os.path.join(subfolder,image),destination_normal)
                else:
                    shutil.copy2(os.path.join(subfolder,image),destination_cancer_benign)
    print("restructuration terminée :)")

In [22]:
restructure_data()

100%|██████████| 5000/5000 [01:19<00:00, 63.15it/s]

restructuration terminée :)

In [ ]:
path="/home/onyxia/work/dataset_vindr"
endpoint_s3 = "s3/lucasvital/stat_app/dataset_vindr"
os.system(f"mc mirror {path} {endpoint_s3}")

print(f"Fichiers synchronisés sur S3 à l'adresse : {endpoint_s3}")

`/home/onyxia/work/dataset_vindr/0-normal/000611f8c6a44659a1813f4019241829.png` -> `s3/lucasvital/stat_app/0-normal/000611f8c6a44659a1813f4019241829.png`
`/home/onyxia/work/dataset_vindr/0-normal/000470cbf12fe2b285cba99286a9a4fa.png` -> `s3/lucasvital/stat_app/0-normal/000470cbf12fe2b285cba99286a9a4fa.png`
`/home/onyxia/work/dataset_vindr/0-normal/0027b96e3fad26237fc3b9a4e3764569.png` -> `s3/lucasvital/stat_app/0-normal/0027b96e3fad26237fc3b9a4e3764569.png`
`/home/onyxia/work/dataset_vindr/0-normal/001fb1c119340b6ae228f4ff68f9ac15.png` -> `s3/lucasvital/stat_app/0-normal/001fb1c119340b6ae228f4ff68f9ac15.png`
`/home/onyxia/work/dataset_vindr/0-normal/0033486d8e272f4914b6e6220b21297f.png` -> `s3/lucasvital/stat_app/0-normal/0033486d8e272f4914b6e6220b21297f.png`
`/home/onyxia/work/dataset_vindr/0-normal/0047aa1ae897453c44092f0552966d04.png` -> `s3/lucasvital/stat_app/0-normal/0047aa1ae897453c44092f0552966d04.png`
`/home/onyxia/work/dataset_vindr/0-normal/0054157b864fdec43a8519c33774ed68.png` -> `s3/lucasvital/stat_app/0-normal/0054157b864fdec43a8519c33774ed68.png`
`/home/onyxia/work/dataset_vindr/0-normal/0055985d501ed5735ad4360dfa91a602.png` -> `s3/lucasvital/stat_app/0-normal/0055985d501ed5735ad4360dfa91a602.png`
`/home/onyxia/work/dataset_vindr/0-normal/0071fb50c07c4c6f49df3667b8715d58.png` -> `s3/lucasvital/stat_app/0-normal/0071fb50c07c4c6f49df3667b8715d58.png`
`/home/onyxia/work/dataset_vindr/0-normal/007e731724c46378037cdb8652d63c7b.png` -> `s3/lucasvital/stat_app/0-normal/007e731724c46378037cdb8652d63c7b.png`
`/home/onyxia/work/dataset_vindr/0-normal/008bf14efd99d9d8cb46589e7d0268e8.png` -> `s3/lucasvital/stat_app/0-normal/008bf14efd99d9d8cb46589e7d0268e8.png`
`/home/onyxia/work/dataset_vindr/0-normal/008c4994c54fe932791aa0d0efc9ecbc.png` -> `s3/lucasvital/stat_app/0-normal/008c4994c54fe932791aa0d0efc9ecbc.png`
`/home/onyxia/work/dataset_vindr/0-normal/00939f7a0c1c324f8314bff9a2bf964c.png` -> `s3/lucasvital/stat_app/0-normal/00939f7a0c1c324f8314bff9a2bf964c.png`
`/home/onyxia/work/dataset_vindr/0-normal/0094342b2d3cf9eeccdda391589c2193.png` -> `s3/lucasvital/stat_app/0-normal/0094342b2d3cf9eeccdda391589c2193.png`
`/home/onyxia/work/dataset_vindr/0-normal/00946f51af23d51b74642c24f131eee5.png` -> `s3/lucasvital/stat_app/0-normal/00946f51af23d51b74642c24f131eee5.png`
`/home/onyxia/work/dataset_vindr/0-normal/00b2567654cfadcda25f5bcbe44f4974.png` -> `s3/lucasvital/stat_app/0-normal/00b2567654cfadcda25f5bcbe44f4974.png`
`/home/onyxia/work/dataset_vindr/0-normal/00b72fc9f66aacea67225c2f4e0c887a.png` -> `s3/lucasvital/stat_app/0-normal/00b72fc9f66aacea67225c2f4e0c887a.png`
`/home/onyxia/work/dataset_vindr/0-normal/00c814300a205bb4e29fb4f7670386bf.png` -> `s3/lucasvital/stat_app/0-normal/00c814300a205bb4e29fb4f7670386bf.png`
`/home/onyxia/work/dataset_vindr/0-normal/00d6335ebcaf795dca3fe958841faf5b.png` -> `s3/lucasvital/stat_app/0-normal/00d6335ebcaf795dca3fe958841faf5b.png`
`/home/onyxia/work/dataset_vindr/0-normal/00d89741d0f25b2b3f69cfca423dbfe1.png` -> `s3/lucasvital/stat_app/0-normal/00d89741d0f25b2b3f69cfca423dbfe1.png`
`/home/onyxia/work/dataset_vindr/0-normal/00db232e4a169350d8531dd3cfb7cab5.png` -> `s3/lucasvital/stat_app/0-normal/00db232e4a169350d8531dd3cfb7cab5.png`
`/home/onyxia/work/dataset_vindr/0-normal/00e82b6a7ad3d0b381640a295364cad0.png` -> `s3/lucasvital/stat_app/0-normal/00e82b6a7ad3d0b381640a295364cad0.png`
`/home/onyxia/work/dataset_vindr/0-normal/00efff24259203a7f19a2875295e4ba6.png` -> `s3/lucasvital/stat_app/0-normal/00efff24259203a7f19a2875295e4ba6.png`
`/home/onyxia/work/dataset_vindr/0-normal/00f84abddd28d62dea9d9ceb3e21ad2d.png` -> `s3/lucasvital/stat_app/0-normal/00f84abddd28d62dea9d9ceb3e21ad2d.png`
`/home/onyxia/work/dataset_vindr/0-normal/00f50221d853cc5f799359c2afe939e7.png` -> `s3/lucasvital/stat_app/0-normal/00f50221d853cc5f799359c2afe939e7.png`
`/home/onyxia/work/dataset_vindr/0-normal/00f93296e26122d3c3bf9dac05485639.png` -> `s3/lucasvital/stat_app/0-normal/00f93296e26122d3c3bf9dac05485639.png`
`/home/onyxia/work/dataset_vindr/0-normal/00ffbfd49b7723c0b03bf13e9c9d3893.png` -> `s3/lucasvital/stat_app/0-normal/00ffbfd49b7723c0b03bf13e9c9d3893.png`
`/home/onyxia/work/dataset_vindr/0-normal/0102ef460bb7a9f7ffe8f3506b5912af.png` -> `s3/lucasvital/stat_app/0-normal/0102ef460bb7a9f7ffe8f3506b5912af.png`
`/home/onyxia/work/dataset_vindr/0-normal/0103fc3489dfc797d8d8552cc6272630.png` -> `s3/lucasvital/stat_app/0-normal/0103fc3489dfc797d8d8552cc6272630.png`
`/home/onyxia/work/dataset_vindr/0-normal/0114af40c446680f1e43d805b0eec249.png` -> `s3/lucasvital/stat_app/0-normal/0114af40c446680f1e43d805b0eec249.png`
`/home/onyxia/work/dataset_vindr/0-normal/011ae2b44e19d1008ad31c02bd9bca62.png` -> `s3/lucasvital/stat_app/0-normal/011ae2b44e19d1008ad31c02bd9bca62.png`
`/home/onyxia/work/dataset_vindr/0-normal/0132d7c1753efb8316f18cd5e6df8e20.png` -> `s3/lucasvital/stat_app/0-normal/0132d7c1753efb8316f18cd5e6df8e20.png`
`/home/onyxia/work/dataset_vindr/0-normal/013574ba096190e923131682ae96d252.png` -> `s3/lucasvital/stat_app/0-normal/013574ba096190e923131682ae96d252.png`
`/home/onyxia/work/dataset_vindr/0-normal/01429480e2f29ce823a77057e316a83d.png` -> `s3/lucasvital/stat_app/0-normal/01429480e2f29ce823a77057e316a83d.png`
`/home/onyxia/work/dataset_vindr/0-normal/0143401573fec5e1779341b6b212959c.png` -> `s3/lucasvital/stat_app/0-normal/0143401573fec5e1779341b6b212959c.png`
`/home/onyxia/work/dataset_vindr/0-normal/014504a6a552f98219ed0a66550abc14.png` -> `s3/lucasvital/stat_app/0-normal/014504a6a552f98219ed0a66550abc14.png`
`/home/onyxia/work/dataset_vindr/0-normal/014566c91fba30f17c700e6616f07942.png` -> `s3/lucasvital/stat_app/0-normal/014566c91fba30f17c700e6616f07942.png`
`/home/onyxia/work/dataset_vindr/0-normal/014c0ffd807ff6b77affde714f20f544.png` -> `s3/lucasvital/stat_app/0-normal/014c0ffd807ff6b77affde714f20f544.png`
`/home/onyxia/work/dataset_vindr/0-normal/014c1e5620abcb4380d582f8545fcaf9.png` -> `s3/lucasvital/stat_app/0-normal/014c1e5620abcb4380d582f8545fcaf9.png`
`/home/onyxia/work/dataset_vindr/0-normal/0153484d2471a8cee37036e37225ba94.png` -> `s3/lucasvital/stat_app/0-normal/0153484d2471a8cee37036e37225ba94.png`
`/home/onyxia/work/dataset_vindr/0-normal/015b30ebc88cd1b2edc5fabdd3817b5e.png` -> `s3/lucasvital/stat_app/0-normal/015b30ebc88cd1b2edc5fabdd3817b5e.png`
`/home/onyxia/work/dataset_vindr/0-normal/015edb61b63eb965121d6167b483786f.png` -> `s3/lucasvital/stat_app/0-normal/015edb61b63eb965121d6167b483786f.png`
`/home/onyxia/work/dataset_vindr/0-normal/0161d5285a337b2a67dcdec29662b231.png` -> `s3/lucasvital/stat_app/0-normal/0161d5285a337b2a67dcdec29662b231.png`
`/home/onyxia/work/dataset_vindr/0-normal/015f3799307f9b33b48366bd4f54306a.png` -> `s3/lucasvital/stat_app/0-normal/015f3799307f9b33b48366bd4f54306a.png`
`/home/onyxia/work/dataset_vindr/0-normal/0176bd63da4d5e932fec5c4d115b0656.png` -> `s3/lucasvital/stat_app/0-normal/0176bd63da4d5e932fec5c4d115b0656.png`
`/home/onyxia/work/dataset_vindr/0-normal/017723bf76418d2db1ae85136df79635.png` -> `s3/lucasvital/stat_app/0-normal/017723bf76418d2db1ae85136df79635.png`
`/home/onyxia/work/dataset_vindr/0-normal/0178810f3d306a7aa66eeea226b85846.png` -> `s3/lucasvital/stat_app/0-normal/0178810f3d306a7aa66eeea226b85846.png`
`/home/onyxia/work/dataset_vindr/0-normal/01937fac58ef0240f3797a5b63903857.png` -> `s3/lucasvital/stat_app/0-normal/01937fac58ef0240f3797a5b63903857.png`
`/home/onyxia/work/dataset_vindr/0-normal/019694a4ae632f53891c466780d3cf56.png` -> `s3/lucasvital/stat_app/0-normal/019694a4ae632f53891c466780d3cf56.png`
`/home/onyxia/work/dataset_vindr/0-normal/01a3a99db634b05fc19f2d06ac49d32b.png` -> `s3/lucasvital/stat_app/0-normal/01a3a99db634b05fc19f2d06ac49d32b.png`
`/home/onyxia/work/dataset_vindr/0-normal/01aa2c5c20ae6adf7df67d797ba3c8f6.png` -> `s3/lucasvital/stat_app/0-normal/01aa2c5c20ae6adf7df67d797ba3c8f6.png`
`/home/onyxia/work/dataset_vindr/0-normal/01acc66739b4f7ea44a1d50db915a900.png` -> `s3/lucasvital/stat_app/0-normal/01acc66739b4f7ea44a1d50db915a900.png`
`/home/onyxia/work/dataset_vindr/0-normal/01b55c2aea91936fea31ba8a488f7b55.png` -> `s3/lucasvital/stat_app/0-normal/01b55c2aea91936fea31ba8a488f7b55.png`
`/home/onyxia/work/dataset_vindr/0-normal/01c1f650419a8bdbe22d8e5b218ba569.png` -> `s3/lucasvital/stat_app/0-normal/01c1f650419a8bdbe22d8e5b218ba569.png`
`/home/onyxia/work/dataset_vindr/0-normal/01d0cd4189c35961f46b5b87adf2fce8.png` -> `s3/lucasvital/stat_app/0-normal/01d0cd4189c35961f46b5b87adf2fce8.png`
`/home/onyxia/work/dataset_vindr/0-normal/01d469ab8f60dda538776c0e1af305ae.png` -> `s3/lucasvital/stat_app/0-normal/01d469ab8f60dda538776c0e1af305ae.png`
`/home/onyxia/work/dataset_vindr/0-normal/01da09fd1965f686f5613d00f749c202.png` -> `s3/lucasvital/stat_app/0-normal/01da09fd1965f686f5613d00f749c202.png`
`/home/onyxia/work/dataset_vindr/0-normal/01e79ce666e00c526e6e6fd6a7a8180a.png` -> `s3/lucasvital/stat_app/0-normal/01e79ce666e00c526e6e6fd6a7a8180a.png`
`/home/onyxia/work/dataset_vindr/0-normal/01ea288cea134b2730c5965888e22b73.png` -> `s3/lucasvital/stat_app/0-normal/01ea288cea134b2730c5965888e22b73.png`
`/home/onyxia/work/dataset_vindr/0-normal/01f8c129f7961372e3906173b34d206f.png` -> `s3/lucasvital/stat_app/0-normal/01f8c129f7961372e3906173b34d206f.png`
`/home/onyxia/work/dataset_vindr/0-normal/0205def375e7d5b45cc8ee505cec0181.png` -> `s3/lucasvital/stat_app/0-normal/0205def375e7d5b45cc8ee505cec0181.png`
`/home/onyxia/work/dataset_vindr/0-normal/0218fff4e564d49dc159fa98db411c50.png` -> `s3/lucasvital/stat_app/0-normal/0218fff4e564d49dc159fa98db411c50.png`
`/home/onyxia/work/dataset_vindr/0-normal/0228a0c3c65d83e70bf133e5ce5adb0f.png` -> `s3/lucasvital/stat_app/0-normal/0228a0c3c65d83e70bf133e5ce5adb0f.png`
`/home/onyxia/work/dataset_vindr/0-normal/023ee59f2ea80dc22c2e3593daeed7f2.png` -> `s3/lucasvital/stat_app/0-normal/023ee59f2ea80dc22c2e3593daeed7f2.png`
`/home/onyxia/work/dataset_vindr/0-normal/023ef76ea06aad586953455a02d75fc5.png` -> `s3/lucasvital/stat_app/0-normal/023ef76ea06aad586953455a02d75fc5.png`
`/home/onyxia/work/dataset_vindr/0-normal/024c725d404a8276ce75c49693705063.png` -> `s3/lucasvital/stat_app/0-normal/024c725d404a8276ce75c49693705063.png`
`/home/onyxia/work/dataset_vindr/0-normal/024df489163da4804002e1b77d7160d1.png` -> `s3/lucasvital/stat_app/0-normal/024df489163da4804002e1b77d7160d1.png`
`/home/onyxia/work/dataset_vindr/0-normal/024f073c6529d7f7b3f95fc589f40d38.png` -> `s3/lucasvital/stat_app/0-normal/024f073c6529d7f7b3f95fc589f40d38.png`
`/home/onyxia/work/dataset_vindr/0-normal/0257c4237cec09614a6a1501c73919d7.png` -> `s3/lucasvital/stat_app/0-normal/0257c4237cec09614a6a1501c73919d7.png`
`/home/onyxia/work/dataset_vindr/0-normal/025a6d27ef782cbe382d3325e0f67689.png` -> `s3/lucasvital/stat_app/0-normal/025a6d27ef782cbe382d3325e0f67689.png`
`/home/onyxia/work/dataset_vindr/0-normal/025deb287a60273e88f13047621df3ba.png` -> `s3/lucasvital/stat_app/0-normal/025deb287a60273e88f13047621df3ba.png`
`/home/onyxia/work/dataset_vindr/0-normal/0263ac33ea388446f5ef9b5d074cd7ac.png` -> `s3/lucasvital/stat_app/0-normal/0263ac33ea388446f5ef9b5d074cd7ac.png`
`/home/onyxia/work/dataset_vindr/0-normal/027244994968b700470e5945b7a801f9.png` -> `s3/lucasvital/stat_app/0-normal/027244994968b700470e5945b7a801f9.png`
`/home/onyxia/work/dataset_vindr/0-normal/028435348a0e7f91f57befc29a898f02.png` -> `s3/lucasvital/stat_app/0-normal/028435348a0e7f91f57befc29a898f02.png`
`/home/onyxia/work/dataset_vindr/0-normal/0298ec4d3be4a903130090de61bcedc2.png` -> `s3/lucasvital/stat_app/0-normal/0298ec4d3be4a903130090de61bcedc2.png`
`/home/onyxia/work/dataset_vindr/0-normal/02bb56abacbecd1df58d7edf6b6bc9ed.png` -> `s3/lucasvital/stat_app/0-normal/02bb56abacbecd1df58d7edf6b6bc9ed.png`
`/home/onyxia/work/dataset_vindr/0-normal/02cb48f8d183982d36ce3d126ba132bc.png` -> `s3/lucasvital/stat_app/0-normal/02cb48f8d183982d36ce3d126ba132bc.png`
`/home/onyxia/work/dataset_vindr/0-normal/02d154f528b82fb59fe9e7b2a049522e.png` -> `s3/lucasvital/stat_app/0-normal/02d154f528b82fb59fe9e7b2a049522e.png`
`/home/onyxia/work/dataset_vindr/0-normal/02d721ad8c872e33065398c929e92726.png` -> `s3/lucasvital/stat_app/0-normal/02d721ad8c872e33065398c929e92726.png`
`/home/onyxia/work/dataset_vindr/0-normal/02de08598e97d5f0eb9d94ae05209cdd.png` -> `s3/lucasvital/stat_app/0-normal/02de08598e97d5f0eb9d94ae05209cdd.png`
`/home/onyxia/work/dataset_vindr/0-normal/02e8a3a33d01acd45a9cf13790ea0324.png` -> `s3/lucasvital/stat_app/0-normal/02e8a3a33d01acd45a9cf13790ea0324.png`
`/home/onyxia/work/dataset_vindr/0-normal/02ea268cddde7cf3a9a88484a9b8d19c.png` -> `s3/lucasvital/stat_app/0-normal/02ea268cddde7cf3a9a88484a9b8d19c.png`
`/home/onyxia/work/dataset_vindr/0-normal/02f0418f8a925fb7086b245c18c31859.png` -> `s3/lucasvital/stat_app/0-normal/02f0418f8a925fb7086b245c18c31859.png`
`/home/onyxia/work/dataset_vindr/0-normal/03136a1057eac8c4ca8cf0300a6aaf0f.png` -> `s3/lucasvital/stat_app/0-normal/03136a1057eac8c4ca8cf0300a6aaf0f.png`
`/home/onyxia/work/dataset_vindr/0-normal/033c3a8952ce3b546b0caf954b1a554f.png` -> `s3/lucasvital/stat_app/0-normal/033c3a8952ce3b546b0caf954b1a554f.png`
`/home/onyxia/work/dataset_vindr/0-normal/034d4806fba1ea27cb26a890364a30ce.png` -> `s3/lucasvital/stat_app/0-normal/034d4806fba1ea27cb26a890364a30ce.png`
`/home/onyxia/work/dataset_vindr/0-normal/034e6d43d17f791c356a5b7766cf2be1.png` -> `s3/lucasvital/stat_app/0-normal/034e6d43d17f791c356a5b7766cf2be1.png`
`/home/onyxia/work/dataset_vindr/0-normal/03551b175c06791d3c1f76a935e58405.png` -> `s3/lucasvital/stat_app/0-normal/03551b175c06791d3c1f76a935e58405.png`
`/home/onyxia/work/dataset_vindr/0-normal/036a4c862065d31d738e69badcd4b066.png` -> `s3/lucasvital/stat_app/0-normal/036a4c862065d31d738e69badcd4b066.png`
`/home/onyxia/work/dataset_vindr/0-normal/037fbbcf60e4ce37080c1390248cbd33.png` -> `s3/lucasvital/stat_app/0-normal/037fbbcf60e4ce37080c1390248cbd33.png`
`/home/onyxia/work/dataset_vindr/0-normal/038a667ad8327337f5d4e32c53c4b82b.png` -> `s3/lucasvital/stat_app/0-normal/038a667ad8327337f5d4e32c53c4b82b.png`
`/home/onyxia/work/dataset_vindr/0-normal/0397ba6ec759c836c0fde966b5b9c369.png` -> `s3/lucasvital/stat_app/0-normal/0397ba6ec759c836c0fde966b5b9c369.png`
`/home/onyxia/work/dataset_vindr/0-normal/039bbfb3c10699372c1eee94826b94af.png` -> `s3/lucasvital/stat_app/0-normal/039bbfb3c10699372c1eee94826b94af.png`
`/home/onyxia/work/dataset_vindr/0-normal/03bc212124aba1eea604e6ae3ce49c3e.png` -> `s3/lucasvital/stat_app/0-normal/03bc212124aba1eea604e6ae3ce49c3e.png`
`/home/onyxia/work/dataset_vindr/0-normal/03c961ba5dc0f32e87ace26cb9884af3.png` -> `s3/lucasvital/stat_app/0-normal/03c961ba5dc0f32e87ace26cb9884af3.png`
`/home/onyxia/work/dataset_vindr/0-normal/03cc93a37e73fc538bfde4c4de4d6dd1.png` -> `s3/lucasvital/stat_app/0-normal/03cc93a37e73fc538bfde4c4de4d6dd1.png`
`/home/onyxia/work/dataset_vindr/0-normal/03ce8b2ed38f04166291966fd188ff5e.png` -> `s3/lucasvital/stat_app/0-normal/03ce8b2ed38f04166291966fd188ff5e.png`
`/home/onyxia/work/dataset_vindr/0-normal/03ddea921f1223e22c0008c3a9d61a09.png` -> `s3/lucasvital/stat_app/0-normal/03ddea921f1223e22c0008c3a9d61a09.png`
`/home/onyxia/work/dataset_vindr/0-normal/03ffb4a465bbf5ed4fcd1f3984a22e4c.png` -> `s3/lucasvital/stat_app/0-normal/03ffb4a465bbf5ed4fcd1f3984a22e4c.png`
`/home/onyxia/work/dataset_vindr/0-normal/0402db785ed85ea3378cebadd14680be.png` -> `s3/lucasvital/stat_app/0-normal/0402db785ed85ea3378cebadd14680be.png`
`/home/onyxia/work/dataset_vindr/0-normal/040497b3aa7a4bd059e593dc4ea26949.png` -> `s3/lucasvital/stat_app/0-normal/040497b3aa7a4bd059e593dc4ea26949.png`
`/home/onyxia/work/dataset_vindr/0-normal/04088fd3f128fa108006cf9fc8b162e2.png` -> `s3/lucasvital/stat_app/0-normal/04088fd3f128fa108006cf9fc8b162e2.png`
`/home/onyxia/work/dataset_vindr/0-normal/040c1ec439cb43a37d2e260ff3be41b6.png` -> `s3/lucasvital/stat_app/0-normal/040c1ec439cb43a37d2e260ff3be41b6.png`
`/home/onyxia/work/dataset_vindr/0-normal/040fb9e96d6619afdb69aae3893bebcb.png` -> `s3/lucasvital/stat_app/0-normal/040fb9e96d6619afdb69aae3893bebcb.png`
`/home/onyxia/work/dataset_vindr/0-normal/041897b571bd2f008bd4c2648d557c6d.png` -> `s3/lucasvital/stat_app/0-normal/041897b571bd2f008bd4c2648d557c6d.png`
`/home/onyxia/work/dataset_vindr/0-normal/0422836ec6d22204429ffc6e9496ba12.png` -> `s3/lucasvital/stat_app/0-normal/0422836ec6d22204429ffc6e9496ba12.png`
`/home/onyxia/work/dataset_vindr/0-normal/0426b1749b083d1d389f8a6391c6f79d.png` -> `s3/lucasvital/stat_app/0-normal/0426b1749b083d1d389f8a6391c6f79d.png`
`/home/onyxia/work/dataset_vindr/0-normal/04321bf9718b3fbcb904aff875422efe.png` -> `s3/lucasvital/stat_app/0-normal/04321bf9718b3fbcb904aff875422efe.png`
`/home/onyxia/work/dataset_vindr/0-normal/0433c111db494f970a6cfb6cb8027f53.png` -> `s3/lucasvital/stat_app/0-normal/0433c111db494f970a6cfb6cb8027f53.png`
`/home/onyxia/work/dataset_vindr/0-normal/043973edc26476a0d82629ec5a166913.png` -> `s3/lucasvital/stat_app/0-normal/043973edc26476a0d82629ec5a166913.png`
`/home/onyxia/work/dataset_vindr/0-normal/0439cef9d78dd8bc8164b6a316caefdc.png` -> `s3/lucasvital/stat_app/0-normal/0439cef9d78dd8bc8164b6a316caefdc.png`
`/home/onyxia/work/dataset_vindr/0-normal/043a2de5fb71a19bb8cd1a96d94188b4.png` -> `s3/lucasvital/stat_app/0-normal/043a2de5fb71a19bb8cd1a96d94188b4.png`
`/home/onyxia/work/dataset_vindr/0-normal/043f8a50170c20d0aaab3810b3941252.png` -> `s3/lucasvital/stat_app/0-normal/043f8a50170c20d0aaab3810b3941252.png`
`/home/onyxia/work/dataset_vindr/0-normal/044ed054e260ed615ee390d790e21d0b.png` -> `s3/lucasvital/stat_app/0-normal/044ed054e260ed615ee390d790e21d0b.png`
`/home/onyxia/work/dataset_vindr/0-normal/045495f52a43b12b8889a1af813bfcfe.png` -> `s3/lucasvital/stat_app/0-normal/045495f52a43b12b8889a1af813bfcfe.png`
`/home/onyxia/work/dataset_vindr/0-normal/0459cb1c4c80b5c4cd4f2edd18e5ff98.png` -> `s3/lucasvital/stat_app/0-normal/0459cb1c4c80b5c4cd4f2edd18e5ff98.png`
`/home/onyxia/work/dataset_vindr/0-normal/04641f4ded035d9cea5310a7c9122287.png` -> `s3/lucasvital/stat_app/0-normal/04641f4ded035d9cea5310a7c9122287.png`
`/home/onyxia/work/dataset_vindr/0-normal/046880cfce60f54f0a82c534e3e4a353.png` -> `s3/lucasvital/stat_app/0-normal/046880cfce60f54f0a82c534e3e4a353.png`
`/home/onyxia/work/dataset_vindr/0-normal/046d21143320b4670c60988239bd030b.png` -> `s3/lucasvital/stat_app/0-normal/046d21143320b4670c60988239bd030b.png`
`/home/onyxia/work/dataset_vindr/0-normal/0487d78751f8a153569bd55ebb27f1c8.png` -> `s3/lucasvital/stat_app/0-normal/0487d78751f8a153569bd55ebb27f1c8.png`
`/home/onyxia/work/dataset_vindr/0-normal/048d09a34cee5ad554b3bf74dec790d5.png` -> `s3/lucasvital/stat_app/0-normal/048d09a34cee5ad554b3bf74dec790d5.png`
`/home/onyxia/work/dataset_vindr/0-normal/0499c489fd29c07f4ed75e296aa54107.png` -> `s3/lucasvital/stat_app/0-normal/0499c489fd29c07f4ed75e296aa54107.png`
`/home/onyxia/work/dataset_vindr/0-normal/049b8ec439f6ca45402c9b2eb216f4ed.png` -> `s3/lucasvital/stat_app/0-normal/049b8ec439f6ca45402c9b2eb216f4ed.png`
`/home/onyxia/work/dataset_vindr/0-normal/04a5d9604fb950aa287f4b77007f2a24.png` -> `s3/lucasvital/stat_app/0-normal/04a5d9604fb950aa287f4b77007f2a24.png`
`/home/onyxia/work/dataset_vindr/0-normal/04a3e79996d3ea13d264d995e25c91c1.png` -> `s3/lucasvital/stat_app/0-normal/04a3e79996d3ea13d264d995e25c91c1.png`
`/home/onyxia/work/dataset_vindr/0-normal/04c5e4b55e51eb4627b7f2c997b62d9f.png` -> `s3/lucasvital/stat_app/0-normal/04c5e4b55e51eb4627b7f2c997b62d9f.png`
`/home/onyxia/work/dataset_vindr/0-normal/04ca0cca9f965745a6ea36af1dabad02.png` -> `s3/lucasvital/stat_app/0-normal/04ca0cca9f965745a6ea36af1dabad02.png`
`/home/onyxia/work/dataset_vindr/0-normal/04d68a4dd17d21a67e6a1c355c67938e.png` -> `s3/lucasvital/stat_app/0-normal/04d68a4dd17d21a67e6a1c355c67938e.png`
`/home/onyxia/work/dataset_vindr/0-normal/04dca70b316e240af7f3aef533944b06.png` -> `s3/lucasvital/stat_app/0-normal/04dca70b316e240af7f3aef533944b06.png`

== WARN: `minio.lab.sspcloud.fr` certificate will expire in 2026-02-26 12:48:48 +0000 UTC. Renew soon to avoid outage.